settings:
  hostname: ""
  RTCPP: 12580
  RUDPP: 12581
  isContinuity: false
  mixture: true
  step: 600
  dataSizeMB: 100
  mysqlAddress: 0HpNlDeO70YTFJxYX7k5qlPpYgtsR1o/25F4MmoLTOw=
  mysqlPassWord: F5BM56YG+SoN4wm0Wo5Mzw==
  useDB: true
  mysqlUser: root
points:
  - address: 39.104.227.118
    alias: Ali_HuHeHaoTe2
    periodPacketNum: 50
    perPacketIntervalMs: 10
    perPacketIntervalUs: 0
    periodNum: 1
    periodMs: 0
  - address: 149.129.130.238
    alias: Ali_bombay
    periodPacketNum: 50
    perPacketIntervalMs: 10
    perPacketIntervalUs: 0
    periodNum: 1
    periodMs: 0
